services:
  envoy:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
    ports:
      - "9901:9901"
      - "8000:8000"

  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile-server
    ports:
      - "5000:5000"
      - "4999:4999"

  grpc_client-react:
    build:
      context: .
      dockerfile: Dockerfile-react
    environment:
      - ASPNETCORE_HTTP_PORTS=5173
    ports:
      - "5173:5173"
 
  # grpc_client-blazor:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-blazor
  #   environment:
  #     - ASPNETCORE_HTTP_PORTS=7299
  #   ports:
  #     - "7299:7299"
