services:
  evoy_gateway:
    build:
      context: .
      dockerfile: Dockerfile-envoy
    environment:
      - ASPNETCORE_HTTP_PORTS=9902
      - ASPNETCORE_GRPC_PORTS=10000
    ports:
      - "9902:9902"
      - "10000:10000"

  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile-server
    environment:
      - ASPNETCORE_HTTP_PORTS=4999
      - ASPNETCORE_GRPC_PORTS=5000
    ports:
      - "5000:5000"
      - "4999:4999"

  grpc_client-react:
    build:
      context: .
      dockerfile: Dockerfile-react
    environment:
      - ASPNETCORE_HTTP_PORTS=5173
    ports:
      - "5173:5173"
 
  grpc_client-blazor:
    build:
      context: .
      dockerfile: Dockerfile-blazor
    environment:
      - ASPNETCORE_HTTP_PORTS=7299
    ports:
      - "7299:7299"
