FROM envoyproxy/envoy-dev:d82453231f89cb021eb716a23805073cff1f7179
FROM    alpine:3.15.1 AS build

WORKDIR /app

EXPOSE 8080
EXPOSE 9901

RUN     apk add --no-cache protoc

COPY    ./RestAndGrpcApp.Shared/Protos/wrappers.proto /app/google/protobuf/wrappers.proto
COPY    ./RestAndGrpcApp.Shared/Protos/timestamp.proto /app/google/protobuf/timestamp.proto
COPY    ./RestAndGrpcApp.Shared/Protos/empty.proto /app/google/protobuf/empty.proto
COPY    ./RestAndGrpcApp.Shared/Protos/weatherForecast.pb /app
COPY    ./RestAndGrpcApp.Shared/Protos/weatherForecast_pb.d.ts /app
COPY    ./RestAndGrpcApp.Shared/Protos/WeatherForecastServiceClientPb.ts /app
COPY    ./RestAndGrpcApp.Shared/Protos/echo_pb.d.ts /app
COPY    ./RestAndGrpcApp.Shared/Protos/EchoServiceClientPb.ts /app

# build proto descriptor
WORKDIR /app

FROM    envoyproxy/envoy:v1.22.0

COPY    --from=build /app/weatherForecast.pb /tmp/