# Stage 1: Build Stage
FROM    mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app

# restore
COPY    ["RestAndGrpcApp.Client.Blazor/RestAndGrpcApp.Client.Blazor.csproj", "RestAndGrpcApp.Client.Blazor/"]
COPY    ["RestAndGrpcApp.Shared/RestAndGrpcApp.Shared.csproj", "RestAndGrpcApp.Shared/"]
RUN     dotnet restore 'RestAndGrpcApp.Client.Blazor/RestAndGrpcApp.Client.Blazor.csproj'

# build
COPY    . .
WORKDIR /app/RestAndGrpcApp.Client.Blazor
RUN     dotnet build RestAndGrpcApp.Client.Blazor.csproj -c Release -o /app/build

## Stage 2: Publish Stage
FROM build AS publish
RUN dotnet publish RestAndGrpcApp.Client.Blazor.csproj -c Release -o /app/publish

# Stage 3: Runtime Stage
FROM    mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
ENV ASPNETCORE_HTTP_PORTS=7299
EXPOSE 7299
COPY    --from=publish /app/publish .
ENTRYPOINT ["dotnet", "RestAndGrpcApp.Client.Blazor.dll"]