FROM	envoyproxy/envoy:v1.31.0
FROM    alpine:3.15.1 AS build
COPY	envoy.yaml /etc/envoy/envoy.yaml

WORKDIR /app

EXPOSE 8080
EXPOSE 9901

RUN     apk add --no-cache protoc

COPY    ./Protos/wrappers.proto ./google/protobuf/wrappers.proto
COPY    ./Protos/timestamp.proto ./google/protobuf/timestamp.proto
COPY    ./Protos/empty.proto ./google/protobuf/empty.proto
COPY    ./RestAndGrpcApp.Shared/Protos/echo.proto .
COPY    ./RestAndGrpcApp.Shared/Protos/weatherForecast.proto .

RUN     protoc --include_imports --include_source_info --descriptor_set_out=echo.pb echo.proto
RUN     protoc --include_imports --include_source_info --descriptor_set_out=weatherForecast.pb weatherForecast.proto

# build proto descriptor
WORKDIR /app

FROM    envoyproxy/envoy:v1.22.0

COPY    --from=build /app/weatherForecast.pb /tmp/
COPY    --from=build /app/echo.pb /tmp/