/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.29.1
// source: RestAndGrpcApp.Shared/Protos/echo.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as RestAndGrpcApp_Shared_Protos_echo_pb from '../../RestAndGrpcApp.Shared/Protos/echo_pb'; // proto import: "RestAndGrpcApp.Shared/Protos/echo.proto"


export class EchoServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorEcho = new grpcWeb.MethodDescriptor(
    '/EchoService/Echo',
    grpcWeb.MethodType.UNARY,
    RestAndGrpcApp_Shared_Protos_echo_pb.EchoRequest,
    RestAndGrpcApp_Shared_Protos_echo_pb.EchoResponse,
    (request: RestAndGrpcApp_Shared_Protos_echo_pb.EchoRequest) => {
      return request.serializeBinary();
    },
    RestAndGrpcApp_Shared_Protos_echo_pb.EchoResponse.deserializeBinary
  );

  echo(
    request: RestAndGrpcApp_Shared_Protos_echo_pb.EchoRequest,
    metadata?: grpcWeb.Metadata | null): Promise<RestAndGrpcApp_Shared_Protos_echo_pb.EchoResponse>;

  echo(
    request: RestAndGrpcApp_Shared_Protos_echo_pb.EchoRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: RestAndGrpcApp_Shared_Protos_echo_pb.EchoResponse) => void): grpcWeb.ClientReadableStream<RestAndGrpcApp_Shared_Protos_echo_pb.EchoResponse>;

  echo(
    request: RestAndGrpcApp_Shared_Protos_echo_pb.EchoRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: RestAndGrpcApp_Shared_Protos_echo_pb.EchoResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/EchoService/Echo',
        request,
        metadata || {},
        this.methodDescriptorEcho,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/EchoService/Echo',
    request,
    metadata || {},
    this.methodDescriptorEcho);
  }

}

